//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory..
        /// </summary>
        public static string DefaultDirectoryBrowserDescription {
            get {
                return ResourceManager.GetString("DefaultDirectoryBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mappings.list.
        /// </summary>
        public static string DefaultMapPath {
            get {
                return ResourceManager.GetString("DefaultMapPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will copy all elements from left that are missing in right from left to right and vice versa.
        /// </summary>
        public static string FullSyncDescription {
            get {
                return ResourceManager.GetString("FullSyncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FullSyncIcon {
            get {
                object obj = ResourceManager.GetObject("FullSyncIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string PathsFontSize {
            get {
                return ResourceManager.GetString("PathsFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string PathsFontSizeInProgressWindow {
            get {
                return ResourceManager.GetString("PathsFontSizeInProgressWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsFilePath {
            get {
                return ResourceManager.GetString("SettingsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to change this value.
        /// </summary>
        public static string SyncIconTooltip {
            get {
                return ResourceManager.GetString("SyncIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will copy all elements from right that are missing in left from right to left.
        /// </summary>
        public static string SyncToLeftDescription {
            get {
                return ResourceManager.GetString("SyncToLeftDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SyncToLeftIcon {
            get {
                object obj = ResourceManager.GetObject("SyncToLeftIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will copy all elements from right that are missing in left from right to left and delete all elements that are present in left but not in right (DELETION HAPPENS ON THE LEFT).
        /// </summary>
        public static string SyncToLeftWithDeletionDescription {
            get {
                return ResourceManager.GetString("SyncToLeftWithDeletionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SyncToLeftWithDeletionIcon {
            get {
                object obj = ResourceManager.GetObject("SyncToLeftWithDeletionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will copy all elements from left that are missing in right from left to right.
        /// </summary>
        public static string SyncToRightDescription {
            get {
                return ResourceManager.GetString("SyncToRightDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SyncToRightIcon {
            get {
                object obj = ResourceManager.GetObject("SyncToRightIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will copy all elements from left that are missing in right from left to right and delete all elements that are present in right but not in left (DELETION HAPPENS ON THE RIGHT).
        /// </summary>
        public static string SyncToRightWithDeletionDescription {
            get {
                return ResourceManager.GetString("SyncToRightWithDeletionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SyncToRightWithDeletionIcon {
            get {
                object obj = ResourceManager.GetObject("SyncToRightWithDeletionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
